### ISSUE TITLE
few tables extra in db

### ISSUE THREAD

**Issue by meghakundu** [mahmoudmohamedramadan/Laravel-Digging-v8#1]
"departments", "category products","phone_numbers" etc these are not relevant to ui models created in app. @mahmoudmohamedramadan

**Comment by mahmoudmohamedramadan** [comment]
Can you explain in more detail

**Comment by meghakundu** [comment]
> Can you explain in more detail

Please can match through the url links in web.php under routes section! The tables mentioned in the comment are somehow not related. Also wish to ask about the dogcollection, how it is used. @mahmoudmohamedramadan

**Comment by mahmoudmohamedramadan** [comment]
If you find real problem related to **Database Relationships**, you can submit a PR.

According to the `DogCollection`:

The main difference BETWEEN the `Resource` and `Collection` is the **Resource** accepts only one **Dog** model instance as explained in the [#98 Line](https://github.com/mahmoudmohamedramadan/Laravel-Digging-v8/blob/main/routes/web.php#L98), unlike the **Collection** where it accepts a collection of **Dogs** as explained in the [#101 Line](https://github.com/mahmoudmohamedramadan/Laravel-Digging-v8/blob/main/routes/web.php#L101), [#104 Line](https://github.com/mahmoudmohamedramadan/Laravel-Digging-v8/blob/main/routes/web.php#L104), and [#107 Line](https://github.com/mahmoudmohamedramadan/Laravel-Digging-v8/blob/main/routes/web.php#L107).


It does not matter which approach you follow because they have the same result.

> [!TIP]
> We use the `Resource`, and `Collection` to change the returned property value, e.g.: We can prefix the name with `Ms.` or `Mrs.` according to some conditions.

For more details read [Eloquent API Resource](https://laravel.com/docs/11.x/eloquent-resources#main-content)
